name: Generate Profile Assets

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Snake -> dist/
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: castrovinicius
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2) Stats card -> dist/
      - name: Generate user stats card
        uses: cicirello/user-statistician@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image-file: dist/github-stats.svg

      # 3) Top langs card -> dist/
      - name: Generate top languages card
        uses: cicirello/user-statistician@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image-file: dist/top-langs.svg

      # 4) Publica
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
